#!/system/bin/sh
# NOT TESTED!

set -e

MODULE=/lib/modules/dhd.ko
FIRMWARE=/etc/rtecdc.bin

load() {
    ls > /dev/null 2>&1 $FIRMWARE || ( echo 2>&1 "samsung: $FIRMWARE not found!" ; exit )
    insmod $MODULE firmware_path=$FIRMWARE nvram_path=/etc/nvram.txt
}

unload() {
    rmmod $MODULE
}

$1


